[build] 
  functions = "src/functions/"

[dev]
  command = "gatsby develop"
  port = 3000

[[redirects]]
  from = "/post"
  to = "/.netlify/functions/post"
  status = 200

[[redirects]]
  from = "/vuistje/*"
  to = "/show?id=:splat"
  status = 302